import Providers from "@/lib/Providers";
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Islamic Elegance",
  description:
    "Islamic Elegance online market. Generated by next app, developer Md. Minhazul Islam Khan",
  keywords: "Islamic Elegance, Online shop, market",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Header />
          <main className="min-h-screen sm:mx-10 mx-5">{children}</main>
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
